### ISSUE TITLE
 Error: Unable to resolve module @shopify/react-native-skia

### ISSUE THREAD

**Issue by surethink** [wuba/wrn-echarts#23]
hi there,

First of all, it seems that I should import SvgChart, { SVGRenderer } from 'wrn-echarts', not 'wrn-echarts/svgChart'?

I imports Svg Chart only,  but when building app, there is an error: Unable to resolve module @shopify/react-native-skia. I don't want to import the skia pkg

needs help
thank you for the library

**Comment by zhiqingchen** [comment]
https://github.com/wuba/wrn-echarts/issues/13#issuecomment-1412365413

**Comment by zhiqingchen** [comment]
https://wuba.github.io/wrn-echarts/docs/advanced-guides/import-individually

for 0.1.4

**Comment by surethink** [comment]
thanks for your reply. it works.

I use GraphChart  to render about 20 more items with avatar image on ios simulator and the chart showed out successfully. but I found the screen was stuck at some time, app became slow after that, even slower than my web view based solution. I'm not sure what happened, can you give me some advice?

just follow the example code, everything is the same except the chart type and data source

import SvgChart, { SVGRenderer } from 'wrn-echarts/lib/module/svgChart';
import * as echarts from 'echarts/core';
import {GraphChart} from 'echarts/charts';

// register extensions
echarts.use([
  GraphChart,
  SVGRenderer,
])

**Comment by zhiqingchen** [comment]
There are still [some known issues](https://github.com/wuba/wrn-echarts/issues/16) with this project, so you can download the [APP](https://github.com/wuba/taro-playground/releases/tag/v1.8.0) to experience it before you start.

**Comment by zhiqingchen** [comment]
Since this issue has been fixed, this issue will be closed and if there are other issues, feel free to open a new issue

**Comment by NguyenHoangMinhkkkk** [comment]
i'm already install RNSvg, then install @wuba/react-native-echarts, but seem like it require Skia even when i don't import anything relative with Skia

![Screenshot 2023-04-14 at 08 44 39](https://user-images.githubusercontent.com/30792140/231919998-b165177f-e804-4f4b-abcd-cd1573c4e8fe.png)

**Comment by zhiqingchen** [comment]
hi @NguyenHoangMinhkkkk have you try
```
import SvgChart, { SVGRenderer } from '@wuba/react-native-echarts/svgChart';
```
